import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { MenuLink } from "@/components/menulink";

export const metadata: Metadata = {
  title: "My Contacts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#080808] text-white">
        <header className="flex h-15 py-8 justify-between items-center bg-[#12273e]">
          <h1 className="px-10 text-4xl font-extrabold">My Contacts</h1>
          <nav>
            <ul className="flex gap-8 px-10 text-lg font-semibold ">
              <li>
                <Link
                  className="ring-2 ring-[#ffffff] rounded-full py-1 hover:bg-[#080808] cursor-pointer px-6"
                  href="/about"
                >
                  About
                </Link>
              </li>
              <li>
                <Link
                  className="ring-2 ring-[#ffffff] rounded-full py-1 hover:bg-[#080808] cursor-pointer px-6"
                  href="/contacts"
                >
                  Contacts
                </Link>
              </li>
            </ul>
          </nav>
        </header>
        <div className="layout">{children}</div>
      </body>
    </html>
  );
}
